# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from model_gateway.protocol import driving_pb2 as model__gateway_dot_protocol_dot_driving__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in model_gateway/protocol/driving_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DrivingModelStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/arena.v1.DrivingModel/HealthCheck',
                request_serializer=model__gateway_dot_protocol_dot_driving__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=model__gateway_dot_protocol_dot_driving__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/arena.v1.DrivingModel/GetModelInfo',
                request_serializer=model__gateway_dot_protocol_dot_driving__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=model__gateway_dot_protocol_dot_driving__pb2.ModelInfo.FromString,
                _registered_method=True)
        self.ResetEpisode = channel.unary_unary(
                '/arena.v1.DrivingModel/ResetEpisode',
                request_serializer=model__gateway_dot_protocol_dot_driving__pb2.ResetEpisodeRequest.SerializeToString,
                response_deserializer=model__gateway_dot_protocol_dot_driving__pb2.ResetEpisodeResponse.FromString,
                _registered_method=True)
        self.Infer = channel.unary_unary(
                '/arena.v1.DrivingModel/Infer',
                request_serializer=model__gateway_dot_protocol_dot_driving__pb2.InferRequest.SerializeToString,
                response_deserializer=model__gateway_dot_protocol_dot_driving__pb2.InferResponse.FromString,
                _registered_method=True)


class DrivingModelServicer:
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Liveness. Cheap and side-effect free.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Identity and, importantly, which sensors this model actually needs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetEpisode(self, request, context):
        """Start a new episode. Any per-episode state is cleared here.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer(self, request, context):
        """One observation in, one action out.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DrivingModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=model__gateway_dot_protocol_dot_driving__pb2.HealthCheckRequest.FromString,
                    response_serializer=model__gateway_dot_protocol_dot_driving__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=model__gateway_dot_protocol_dot_driving__pb2.GetModelInfoRequest.FromString,
                    response_serializer=model__gateway_dot_protocol_dot_driving__pb2.ModelInfo.SerializeToString,
            ),
            'ResetEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetEpisode,
                    request_deserializer=model__gateway_dot_protocol_dot_driving__pb2.ResetEpisodeRequest.FromString,
                    response_serializer=model__gateway_dot_protocol_dot_driving__pb2.ResetEpisodeResponse.SerializeToString,
            ),
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=model__gateway_dot_protocol_dot_driving__pb2.InferRequest.FromString,
                    response_serializer=model__gateway_dot_protocol_dot_driving__pb2.InferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arena.v1.DrivingModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arena.v1.DrivingModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DrivingModel:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.v1.DrivingModel/HealthCheck',
            model__gateway_dot_protocol_dot_driving__pb2.HealthCheckRequest.SerializeToString,
            model__gateway_dot_protocol_dot_driving__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.v1.DrivingModel/GetModelInfo',
            model__gateway_dot_protocol_dot_driving__pb2.GetModelInfoRequest.SerializeToString,
            model__gateway_dot_protocol_dot_driving__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.v1.DrivingModel/ResetEpisode',
            model__gateway_dot_protocol_dot_driving__pb2.ResetEpisodeRequest.SerializeToString,
            model__gateway_dot_protocol_dot_driving__pb2.ResetEpisodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.v1.DrivingModel/Infer',
            model__gateway_dot_protocol_dot_driving__pb2.InferRequest.SerializeToString,
            model__gateway_dot_protocol_dot_driving__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
